### ISSUE TITLE
Error when using read only fs container

### ISSUE THREAD

**Issue by plachta11b** [longhorn/benchmark#11]
There is a file written to container FS without using temporary PVC.

```
TEST_FILE: /volume/test
TEST_OUTPUT_PREFIX: test_device
TEST_SIZE: 30G
Benchmarking iops.fio into test_device-iops.json
fio: output file open error: Permission denied
```

Workaroud used:

```
        volumeMounts:
        ...
        - name: fio
          mountPath: /[/fio/] # What the path!
      volumes:
      ...
      - name: fio
        emptyDir: {}
```
